services:
  db:
    image: postgres:latest
    container_name: my_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_service
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-guest}  # Пользователь, заданный через .env, или guest по умолчанию
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-guest}  # Пароль, заданный через .env, или guest по умолчанию
    ports:
      - "5672:5672"       # Порт для RabbitMQ (AMQP протокол)
      - "15672:15672"     # Порт для RabbitMQ Management Console

  migrate:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: photo_migrate
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    command: ["sh", "-c", "sleep 10 && alembic upgrade head"]
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: web_photo_service
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - rabbitmq

volumes:
  pgdata:
